/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 2.16.0 from webgme on Thu Nov 09 2017 10:13:08 GMT-0600 (Central Standard Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'q', // THe promise library..
    'common/storage/constants', // These will be needed to check that the commit did update the branch..
    'webgme-dss/parseSimulationData'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase,
    Q,
    STORAGE_CONSTANTS,
    simDataHelpers) {
    'use strict';

    let fs = require('fs'),
        path = require('path'),
        cp = require('child_process'),
        os = require('os'),
        generateInfoFile = simDataHelpers.generateInfoFile;

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of SimulateModelica.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin SimulateModelica.
     * @constructor
     */
    function SystemSimulator() {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    }

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructue etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    SystemSimulator.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    SystemSimulator.prototype = Object.create(PluginBase.prototype);
    SystemSimulator.prototype.constructor = SystemSimulator;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    SystemSimulator.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        let self = this,
            logger = this.logger,
            modelNode = self.activeNode;

        let resultNode = self.core.getParent(modelNode);

        function generateDirectory(modelName) {
            let MAX_DIR_TRIES = 100,
                result;

            //Ensure top directory exists
            try {
                fs.mkdirSync('outputs');
            } catch (e) {
                if (e.code !== 'EEXIST') {
                    // We do expect the directory to exists
                    throw e;
                }
            }

            let dirname = modelName + '_' + Date.now();

            for (let i = 0; i < MAX_DIR_TRIES; i += 1) {
                result = path.join('outputs', dirname + '__' + i);
                try {
                    fs.mkdirSync(result);
                    break; // The directory was created!
                } catch (e) {
                    if (e.code !== 'EEXIST') {
                        throw e;
                    } else if (i === MAX_DIR_TRIES -1) {
                        throw new Error('Failed to generate unique output directory after ' + MAX_DIR_TRIES + 'attempts!');
                    }
                }
            }

            return result;
        }

        function writeFiles(dir, moFileContent, modelName, stopTime) {
            fs.writeFileSync(path.join(dir, modelName + '.mo'), moFileContent);
            fs.writeFileSync(path.join(dir, 'simulate.mos'), [
                'loadModel(Modelica); getErrorString();',
                'loadFile("' + modelName + '.mo"); getErrorString();',
                'simulate(' + modelName + ', startTime=0.0, stopTime=' + stopTime + ', outputFormat="csv"); getErrorString();'
            ].join('\n'));
        }

        function simulateModel(dir, modelName) {
            let command;
            if (os.platform().indexOf('win') === 0) {
                command = '%OPENMODELICAHOME%\\bin\\omc.exe simulate.mos';
            } else {
                command = 'omc simulate.mos';
            }

            // ninvoke turns exec into a promise call...
            return Q.ninvoke(cp, 'exec', command, {cwd: dir})
                .then(function (res) {
                    logger.info(res);

                    return {
                        dir: dir,
                        resultFileName: generateInfoFile(path.join(dir, modelName)),
                        stdout: res[0],
                        stderr: res[1]
                    };
                });
        }

        // Identified by the plugin id
        self.invokePlugin('ModelicaCodeGenerator')
            .then(function (result) {
                if (result.getSuccess() !== true) {
                    throw new Error('ModelicaCodeGenerator did not return with success!');
                }

                let moFileHash = result.getArtifacts()[0]; // Array of hashes we know only one was added..

                self.result.addArtifact(moFileHash); // Return the mo-file to the user as well..

                return self.blobClient.getObjectAsString(moFileHash);
            })
            .then(function (moFileContent) {
                logger.info('moFileContent', moFileContent);
                let modelName = self.core.getAttribute(modelNode, 'name');

                let dir = generateDirectory(modelName);

                // Write out the files..
                writeFiles(dir, moFileContent, modelName, self.getCurrentConfig().stopTime);

                return simulateModel(dir, modelName);
            })
            .then(function (res) {
                let resJson = fs.readFileSync(res.resultFileName, 'utf-8');
                //return self.blobClient.putFile(res.resultFileName, fs.readFileSync(res.resultFileName));
                return {
                    resInfo: resJson,
                    stdout: res.stdout
                };
            })
            .then(function (res) {
                self.core.setAttribute(resultNode, 'simRes', res.resInfo);
                self.core.setAttribute(resultNode, 'stdout', res.stdout);

                logger.info('Will save results to model..');

                return self.save('Attached simulation results at ' + self.core.getPath(resultNode));
            })
            // .then(function (resInfoHash) {
            //     self.core.setAttribute(resultNode, 'simRes', resInfoHash);
            //
            //     return self.save('Attached simulation results at ' + self.core.getPath(resultNode));
            // })
            .then(function (commitResult) {
                if (commitResult.status === STORAGE_CONSTANTS.SYNCED) {
                    self.result.setSuccess(true);
                    callback(null, self.result);
                } else {
                    self.createMessage(modelNode, 'Simulation succeeded but commit did not update branch.');
                    callback(new Error('Did not update branch.'), self.result);
                }
            })
            .catch(function (err) {
                // Result success is false at invocation.
                callback(err, self.result);
            });

    };

    return SystemSimulator;
});
